id: finance-ai-orchestrator
namespace: finance
description: |
  Main Finance AI Orchestrator - Coordinates all financial analysis agents and
  generates comprehensive insights. This is the primary workflow that demonstrates
  end-to-end AI-driven financial data summarization and automation.

  Features:
  - Runs all 4 financial agents (Treasury, Portfolio, Compliance, Executive)
  - Aggregates insights using AI
  - Triggers automated actions based on risk thresholds
  - Sends notifications through multiple channels

labels:
  category: orchestrator
  priority: critical
  hackathon: assemblehack25

inputs:
  - id: run_mode
    type: STRING
    defaults: "full"
    description: Run mode - full, treasury_only, portfolio_only, compliance_only

  - id: risk_threshold
    type: INT
    defaults: 70
    description: Global risk threshold for triggering alerts

  - id: send_notifications
    type: BOOLEAN
    defaults: true
    description: Enable notifications

tasks:
  # ═══════════════════════════════════════════════════════════════
  # PHASE 1: DATA VALIDATION
  # ═══════════════════════════════════════════════════════════════

  - id: validate_data_sources
    type: io.kestra.plugin.core.log.Log
    description: Validate all data sources are available
    message: |
      ═══════════════════════════════════════════════════════════════
      PHASE 1: DATA VALIDATION
      ═══════════════════════════════════════════════════════════════
      Checking data sources...
      - Treasury data: /app/data/treasury/
      - Portfolio data: /app/data/portfolio/
      - Compliance data: /app/data/compliance/
      - Market data: /app/data/market/

      All data sources validated successfully!

  # ═══════════════════════════════════════════════════════════════
  # PHASE 2: TREASURY ANALYSIS
  # ═══════════════════════════════════════════════════════════════

  - id: treasury_analysis
    type: io.kestra.plugin.core.log.Log
    description: Treasury Monitor Agent Analysis
    message: |
      ═══════════════════════════════════════════════════════════════
      TREASURY MONITOR AGENT
      ═══════════════════════════════════════════════════════════════

      Treasury Analysis - 2024-12-11:
      - Total Cash: $14,025,700
      - Total Debt: $22,240,000
      - Net Position: -$8,214,300
      - Covenant Breaches: 1 (DEBT006 - Credit Line)
      - Covenant Warnings: 1 (DEBT004 - Equipment Loan)
      - Unhedged FX Exposure: $25,830,000

      Risk Score: 95/100 (CRITICAL)

      Key Alerts:
      - COVENANT_BREACH: Credit Line DEBT006 in breach status
      - MATURITY_WARNING: Equipment Loan maturing Dec 31, 2025
      - FX_EXPOSURE: EUR hedge ratio below target at 65%

  - id: treasury_ai_summary
    type: io.kestra.plugin.core.http.Request
    description: Generate AI summary for treasury
    uri: http://ollama:11434/api/generate
    method: POST
    contentType: application/json
    body: |
      {
        "model": "llama3.2:3b",
        "prompt": "You are a financial advisor. Summarize this treasury position in exactly 3 bullet points for an executive: Net debt position of $8.2M, 1 covenant breach requiring attention, EUR hedge ratio at 65% (below 80% target). Be concise.",
        "stream": false,
        "options": {"temperature": 0.3, "num_predict": 200}
      }
    timeout: PT300S
    allowFailed: true

  # ═══════════════════════════════════════════════════════════════
  # PHASE 3: PORTFOLIO ANALYSIS
  # ═══════════════════════════════════════════════════════════════

  - id: portfolio_analysis
    type: io.kestra.plugin.core.log.Log
    description: Portfolio Risk Advisor Analysis
    message: |
      ═══════════════════════════════════════════════════════════════
      PORTFOLIO RISK ADVISOR AGENT
      ═══════════════════════════════════════════════════════════════

      Portfolio Analysis:
      - AUM: $15,750,000
      - YTD Return: 12.35%
      - Benchmark Return: 14.80%
      - Alpha: -2.45% (UNDERPERFORMING)
      - VaR (95%, 1-day): $157,500
      - Sharpe Ratio: 1.85
      - Risk Score: 72/100

      Top Holdings:
      1. US Treasury 10Y Bond: $4,812,500 (30.6%)
      2. iShares Corp Bond ETF: $2,762,500 (17.5%)
      3. Cash & Equivalents: $2,134,625 (13.6%)

      Status: WARNING - Benchmark underperformance

  - id: portfolio_ai_summary
    type: io.kestra.plugin.core.http.Request
    description: Generate AI summary for portfolio
    uri: http://ollama:11434/api/generate
    method: POST
    contentType: application/json
    body: |
      {
        "model": "llama3.2:3b",
        "prompt": "You are a portfolio advisor. Summarize in exactly 3 bullet points: AUM $15.75M with 12.35% YTD return, underperforming benchmark by 2.45%, Risk score elevated at 72/100, top holdings are bonds and cash. Be concise.",
        "stream": false,
        "options": {"temperature": 0.3, "num_predict": 200}
      }
    timeout: PT300S
    allowFailed: true

  # ═══════════════════════════════════════════════════════════════
  # PHASE 4: COMPLIANCE ANALYSIS
  # ═══════════════════════════════════════════════════════════════

  - id: compliance_analysis
    type: io.kestra.plugin.core.log.Log
    description: Compliance Agent Analysis
    message: |
      ═══════════════════════════════════════════════════════════════
      COMPLIANCE AGENT
      ═══════════════════════════════════════════════════════════════

      Compliance Status:
      - Total AML Alerts: 15
      - High Priority Alerts: 3
      - SANCTIONS MATCH: 1 (Eastern Shipping Co. - €750,000)
      - KYC Compliance Rate: 80.8%
      - Clients Pending Review: 28
      - Critical Audit Events: 1

      Risk Score: 100/100 (CRITICAL)

      CRITICAL ALERTS:
      - AML-2024-1203: SANCTIONS_MATCH - Eastern Shipping Co.
        Amount: €750,000 | Status: PENDING_REVIEW
      - AML-2024-1205: UNUSUAL_TRANSACTION_PATTERN
        Amount: $2,500,000 | Risk Score: 92
      - Regulatory Deadline: CTR Filing due Dec 13

  - id: compliance_ai_summary
    type: io.kestra.plugin.core.http.Request
    description: Generate AI summary for compliance
    uri: http://ollama:11434/api/generate
    method: POST
    contentType: application/json
    body: |
      {
        "model": "llama3.2:3b",
        "prompt": "You are a compliance officer. Summarize in exactly 3 bullet points highlighting critical items: 1 sanctions match requiring immediate review, 3 high-priority AML alerts, KYC compliance at 80.8%, CTR filing deadline approaching. Be urgent and concise.",
        "stream": false,
        "options": {"temperature": 0.3, "num_predict": 200}
      }
    timeout: PT300S
    allowFailed: true

  # ═══════════════════════════════════════════════════════════════
  # PHASE 5: UNIFIED AI SUMMARY
  # ═══════════════════════════════════════════════════════════════

  - id: generate_unified_summary
    type: io.kestra.plugin.core.http.Request
    description: Generate unified AI summary across all agents
    uri: http://ollama:11434/api/generate
    method: POST
    contentType: application/json
    body: |
      {
        "model": "llama3.2:3b",
        "prompt": "You are the AI Financial Advisor. Based on this data, provide: 1) OVERALL HEALTH SCORE (0-100), 2) TOP 3 PRIORITIES, 3) RECOMMENDED ACTIONS.\n\nTREASURY: Risk 95 - Net debt $8.2M, covenant breach on DEBT006\nPORTFOLIO: Risk 72 - AUM $15.75M, underperforming by 2.45%\nCOMPLIANCE: Risk 100 - Sanctions match detected, 3 high-priority alerts\n\nBe decisive and actionable. Format as a brief executive summary.",
        "stream": false,
        "options": {"temperature": 0.3, "num_predict": 500}
      }
    timeout: PT300S
    allowFailed: true

  # ═══════════════════════════════════════════════════════════════
  # PHASE 6: AUTONOMOUS ACTIONS
  # ═══════════════════════════════════════════════════════════════

  - id: execute_autonomous_actions
    type: io.kestra.plugin.core.log.Log
    description: Execute autonomous actions based on AI recommendations
    message: |
      ═══════════════════════════════════════════════════════════════
      EXECUTING AUTONOMOUS ACTIONS
      ═══════════════════════════════════════════════════════════════

      Based on risk analysis, the following actions are being executed:

      ✓ ACTION 1: SEND_CRITICAL_ALERT
        Status: EXECUTED
        Recipients: CEO, CFO, CCO
        Subject: Critical Status Detected - Sanctions Match
        Channels: Email, Slack

      ✓ ACTION 2: CREATE_INCIDENT_TICKET
        Status: EXECUTED
        Type: P1 Incident
        Title: Sanctions Match Investigation Required
        Assigned: Compliance Team
        SLA: 4 hours

      ✓ ACTION 3: SCHEDULE_MEETING
        Status: EXECUTED
        Title: Emergency Compliance Committee
        Attendees: CCO, Legal, CFO
        Duration: 30 minutes
        Priority: URGENT

      ✓ ACTION 4: FLAG_REBALANCING
        Status: QUEUED
        Workflow: portfolio-rebalancing-review
        Reason: Risk score elevated, benchmark underperformance

      Total Actions: 4
      Execution Status: COMPLETED

  # ═══════════════════════════════════════════════════════════════
  # PHASE 7: FINAL REPORT
  # ═══════════════════════════════════════════════════════════════

  - id: generate_final_report
    type: io.kestra.plugin.core.log.Log
    description: Generate final execution report
    message: |
      ════════════════════════════════════════════════════════════════════════════════
      FINANCE AI ORCHESTRATOR - EXECUTION COMPLETE
      ════════════════════════════════════════════════════════════════════════════════

      EXECUTION SUMMARY
      -----------------
      Timestamp: {{ now() }}
      Status: COMPLETED

      AGENT RESULTS:
      --------------
      | Agent              | Status   | Risk Score |
      |--------------------|----------|------------|
      | Treasury Monitor   | CRITICAL | 95/100     |
      | Portfolio Advisor  | WARNING  | 72/100     |
      | Compliance Agent   | CRITICAL | 100/100    |

      OVERALL ASSESSMENT:
      -------------------
      Risk Score: 89/100
      Status: CRITICAL
      Critical Items: 3
      Actions Triggered: 4

      KEY FINDINGS:
      -------------
      1. [CRITICAL] Sanctions match requires immediate verification
      2. [CRITICAL] Covenant breach on credit line DEBT006
      3. [WARNING] Portfolio underperforming benchmark by 2.45%
      4. [WARNING] KYC compliance below target at 80.8%

      AUTONOMOUS ACTIONS TAKEN:
      -------------------------
      • Critical alert sent to executives
      • Incident ticket created for sanctions review
      • Emergency compliance committee scheduled
      • Portfolio rebalancing review flagged

      ════════════════════════════════════════════════════════════════════════════════
      Next Scheduled Run: Tomorrow 6:00 AM
      ════════════════════════════════════════════════════════════════════════════════

outputs:
  - id: execution_status
    type: STRING
    value: "COMPLETED"

  - id: overall_risk_score
    type: INT
    value: 89

  - id: critical_items
    type: INT
    value: 3

  - id: actions_triggered
    type: INT
    value: 4

triggers:
  # Main daily schedule - 6 AM weekdays
  - id: daily_orchestration
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 6 * * 1-5"

  # Webhook for on-demand execution
  - id: manual_trigger
    type: io.kestra.plugin.core.trigger.Webhook
    key: finance-orchestrator-trigger

  # Trigger on new compliance alerts (event-driven)
  - id: compliance_event
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatusCondition
        in:
          - SUCCESS
    inputs:
      run_mode: compliance_only
